version: '3'
services:

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: fastapi_microservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - test_network
    ports:
      - "5432:5432"

  app:
    image: fast-api
    container_name: fast-api
    build: /home/cygnet/Documents/arya_git/Fast_api_deploy
    networks:
      - test_network
    depends_on:
      - postgres   
    ports:
      - "8000:8000" 
  

networks:
  test_network:
    driver: bridge

volumes:
  postgres_data:
